<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ropa [
    <!ELEMENT ropa (nombre, color*)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
]>

<ropa>
    <nombre>guante y bufanda</nombre>
    <color>rojo</color>
    <color>blanco</color>
    <color>verde</color>
    <color>azul</color>
</ropa>