<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socios [
<!ELEMENT socios (socio*)>
<!ELEMENT socio ((numero, clave) | (clave, numero)? | (nombre, edad))>
<!ELEMENT clave (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
]>
<socios>
    <socio>
        <nombre>Ana</nombre>
        <edad>21</edad>
    </socio>
    <socio>
        <numero>598</numero>
        <clave>hY75Du</clave>
        <nombre>Iker</nombre>
        <edad>19</edad>
    </socio>
    <socio>
        <clave>hY75Du</clave>
        <nombre>Iker</nombre>
    </socio>
</socios>
