<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seguridadSocial[
<!ELEMENT seguridadSocial (afiliado+)>
<!ELEMENT afiliado (DNI, NIE?, nombre, apellidos, situacion_laboral, fecha_nacimiento, listado_bajas, listado_prestaciones)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT NIE (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT situacion_laboral (#PCDATA)>
<!ATTLIST situacion_laboral tipo (en_paro | en_activo | jubilado | edad_no_laboral) #REQUIRED>
<!ELEMENT fecha_nacimiento EMPTY>
<!ATTLIST fecha_nacimiento dia CDATA #REQUIRED mes CDATA #REQUIRED anyo CDATA #REQUIRED>
<!ELEMENT listado_bajas (baja_empleado)>
<!ELEMENT baja_empleado EMPTY>
<!ATTLIST baja_empleado causa CDATA #REQUIRED fecha_inicio CDATA #REQUIRED fecha_final CDATA #IMPLIED>
<!ELEMENT listado_prestaciones (cobradas)>
<!ELEMENT cobradas EMPTY>
<!ATTLIST cobradas cantidad CDATA #REQUIRED fecha_inicio CDATA #REQUIRED fecha_final CDATA #REQUIRED>
]>

<seguridadSocial>
    <afiliado>
        <DNI>54463341</DNI>
        <nombre>PEPA</nombre>
        <apellidos>GARCÍA GÓMEZ</apellidos>
        <situacion_laboral tipo="en_paro"></situacion_laboral>
        <fecha_nacimiento dia="22" mes="2" anyo="2022"/>
        <listado_bajas>
            <baja_empleado causa="paro" fecha_inicio="22-2-2022"></baja_empleado>
        </listado_bajas>
        <listado_prestaciones>
            <cobradas cantidad="213" fecha_inicio="21-3-2012" fecha_final="5-2-2019"></cobradas>
        </listado_prestaciones>
    </afiliado>
</seguridadSocial>
